#Postgresql
spring.datasource.url=jdbc:postgresql://dpg-d6jashq4d50c73ej85jg-a.singapore-postgres.render.com/moneymanager_zq0y
spring.datasource.username=moneymanager_zq0y_user
spring.datasource.password=5atwUqlP0oeAmcrcuxZTJNF3yKL0RypC
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
